import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import http from 'node:http';
import {collectSite}from'../collectors/index.mjs';import{reviewFindings,validateEvidence,validateSchema,validateConsistency,createRun,saveStage,resumeRun}from'../orchestration/core.mjs';import{generateReports,planFindings}from'../reporters/index.mjs';
test('offline browser evidence -> reviewed finding -> planner -> complete report artifacts -> resume',async()=>{
 const server=http.createServer((req,res)=>{if(req.url==='/robots.txt'){res.setHeader('Content-Type','text/plain');res.end('User-agent: *\nAllow: /\n');return;}if(req.url==='/sitemap.xml'){res.setHeader('Content-Type','application/xml');res.end('<?xml version="1.0"?><urlset></urlset>');return;}res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><html lang="en"><head><title>Fixture shop</title></head><body><h1>Fixture</h1><p>Fixture content</p><a href="/checkout/cart/add?product=1">Unsafe fixture link</a><button>Inspect</button></body></html>');});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const target=`http://127.0.0.1:${server.address().port}/`;const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'addp-integration-'));const id='local-integration';
 try{
  const manifest={RUN_ID:id,timestamp:new Date().toISOString(),target,environment:'fixture',stage_status:{},safety_flags:{AUDIT_ALLOW_REAL_ORDER:false,AUDIT_ALLOW_REAL_PAYMENT:false,AUDIT_ALLOW_ACCOUNT_CREATION:false,AUDIT_ALLOW_DESTRUCTIVE_ACTION:false},safety_outcomes:{real_orders:0,real_payments:0,accounts_created:0,forms_submitted:0,website_changes:0},effective_models:null};
  const runDir=await createRun(tmp,id,manifest);const config={maxPages:1,maxDepth:0,requestDelayMs:0,settleMs:50,browserExecutable:'C:/Program Files/Google/Chrome/Application/chrome.exe',viewports:[{name:'desktop',width:1000,height:800},{name:'mobile',width:390,height:844}]};
  const result=await collectSite({target,runDir,config});assert.equal(result.pages.length,1);assert.ok(result.evidence.length>=15);assert.deepEqual(await validateEvidence(result.evidence,runDir),[]);
  const requirement={id:'REQ-fixture',source:'checklist',requirement:'Fixture metadata requirement',original_text:'Fixture requires a description.',category:'fixture'};
  const evidence=result.evidence.find(e=>e.type==='raw_seo');assert.ok(evidence);const seo=JSON.parse(await fs.readFile(path.join(runDir,evidence.artifact),'utf8'));assert.equal(seo.meta_description,null);
  const finding={finding_id:'FND-FIXTURE-001',title:'Fixture description missing',area:'seo',page:target,page_type:'homepage',source_requirement_ids:[requirement.id],source:'checklist',finding_type:'deterministic',observation:'Fixture HTML contains no meta description.',evidence_ids:[evidence.evidence_id],impact:{user:null,business:null,seo:'Snippet control',technical:null},severity:'low',confidence:1,suggested_direction:'Add a descriptive summary.',unknowns:[],review:{status:'accepted',supported:true,reason:'Verified in local fixture raw metadata.'}};
  const reviewed=await reviewFindings([finding],result.evidence,[requirement],runDir,[{finding_id:finding.finding_id,status:'accepted',supported:true,reason:'Verified in local fixture raw metadata.',reviewer_role:'evidence_reviewer',reviewer_id:'fixture-reviewer',evidence_ids_reviewed:[evidence.evidence_id],supported_facts:['meta_description is null in raw SEO artifact'],observation_reviewed:finding.observation,page_reviewed:finding.page,source_requirement_ids_reviewed:finding.source_requirement_ids}]);assert.equal(reviewed.accepted.length,1);
  const diagnostics=[{finding_id:finding.finding_id,observed_problem:finding.observation,confirmed_external_facts:['No meta description in fixture response'],probable_technical_causes:[],developer_investigation:['Inspect metadata authoring in an authorized source environment'],implementation_area:['CMS/content'],confidence:1}];assert.equal(validateSchema('technical-diagnostic',diagnostics[0]).valid,true);
  const backlog=planFindings(reviewed.accepted,diagnostics);const checks=[{requirement_id:requirement.id,status:'FAIL',evidence_ids:[evidence.evidence_id],observation:finding.observation}];
  const data={runDir,manifest,pages:result.pages,evidence:result.evidence,requirements:[requirement],checks,journeys:[{persona:'fixture',goal:'Inspect homepage',entry_url:target,steps:[{url:target,action:'navigation',outcome:'Fixture visible'}],clicks:0,pages_visited:[target],blockers:[],confusion_points:[],positive_signals:['Content rendered'],completion_status:'complete',evidence_ids:[evidence.evidence_id]}],accepted:reviewed.accepted,manualReview:[],blocked:[],diagnostics,backlog};
  await generateReports(data);for(const name of ['AUDIT_REPORT.md','IMPROVEMENT_PLAN.md','EXECUTIVE_PLAN.md']){const report=await fs.readFile(path.join(runDir,'reports',name),'utf8');assert.ok(report.includes(id),name+' must identify its run');if(name!=='EXECUTIVE_PLAN.md')assert.ok(report.includes(finding.finding_id),name+' must trace to finding');}
  assert.ok((await fs.stat(path.join(runDir,'backlog/DEPENDENCIES.json'))).size>0);const validation=await validateConsistency(data);assert.deepEqual(validation.errors,[]);
  await saveStage(runDir,'fixture','complete');const resumed=await resumeRun(tmp,id);assert.equal(resumed.manifest.stage_status.fixture.status,'complete');assert.equal((await fs.stat(path.join(runDir,evidence.artifact))).isFile(),true);
 }finally{await new Promise(r=>server.close(r));}
});
