import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { startFixture } from '../fixtures/site.mjs'; import { collectRequestedPages } from '../collectors/index.mjs'; import { writeSmokeSummary } from '../orchestration/smoke.mjs';
import { newAudit } from '../orchestration/pipeline.mjs';
const config={browserExecutable:'C:/Program Files/Google/Chrome/Application/chrome.exe',viewports:[{name:'desktop',width:800,height:600},{name:'mobile',width:390,height:844}],settleMs:10,renderAssetTimeoutMs:500,maxScrollIterations:4,totalRenderBudgetMs:4000};
test('direct smoke honors explicit URL boundary, robots, summary and mutation safety', {timeout:60000}, async t=>{
 const fixture=await startFixture(); const runDir=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-'));
 t.after(async()=>{await fixture.close();await fs.rm(runDir,{recursive:true,force:true})});
 const urls=[fixture.target,new URL('/product/glucare-plus',fixture.target).href];
 const result=await collectRequestedPages({target:fixture.target,urls,runDir,config});
 assert.equal(result.pages.length,2); assert.deepEqual(result.pages.map(p=>p.requested_url),urls);
 assert.equal(fixture.requests.some(r=>r.path==='/sitemap.xml'),false,JSON.stringify(fixture.requests));
 for(const forbidden of ['/category','/news/article','/contact','/product/dovital']) assert.equal(fixture.requests.some(r=>r.path===forbidden),false,`${forbidden}: ${JSON.stringify(fixture.requests)}`);
 assert.equal(fixture.requests.some(r=>r.method!=='GET'),false,JSON.stringify(fixture.requests));
 const selection=JSON.parse(await fs.readFile(path.join(runDir,'inventory/selection.json')));
 assert.equal(selection.discovery_expansion,false); assert.deepEqual(selection.requested_urls,urls);
 const summary=await writeSmokeSummary(runDir,urls); assert.equal(summary.entries.length,4);
 for(const entry of summary.entries){assert.ok(entry.requested_url);assert.ok(entry.first_viewport.captured);assert.equal(entry.performance_clean_load.synthetic_scroll_before_measurement,false,JSON.stringify(entry));assert.ok(entry.scroll_stabilized.evidence_ids.length);assert.ok(['complete','partial'].includes(entry.collection_status));}
});
test('direct smoke rejects invalid explicit URL sets before collection', async()=>{const fixture=await startFixture();const runDir=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-invalid-'));try{await assert.rejects(collectRequestedPages({target:fixture.target,urls:[new URL('/cart/add',fixture.target).href],runDir,config}),/Blocked read-only/);await assert.rejects(collectRequestedPages({target:fixture.target,urls:['https://example.com/'],runDir,config}),/same-origin/);}finally{await fixture.close();await fs.rm(runDir,{recursive:true,force:true})}});
test('direct smoke accepts one and three explicit URLs without sitemap or link expansion', {timeout:60000}, async t=>{const fixture=await startFixture();const root=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-count-'));t.after(async()=>{await fixture.close();await fs.rm(root,{recursive:true,force:true})});for(const paths of [['/'],['/','/product/glucare-plus','/news/article']]){fixture.requests.length=0;const runDir=path.join(root,String(paths.length));const urls=paths.map(p=>new URL(p,fixture.target).href);const result=await collectRequestedPages({target:fixture.target,urls,runDir,config});assert.equal(result.pages.length,urls.length);assert.deepEqual(result.pages.map(p=>p.requested_url),urls);assert.equal(fixture.requests.some(r=>r.path==='/sitemap.xml'),false);}});
test('direct smoke rejects empty and four URL sets before robots or browser collection', async()=>{const fixture=await startFixture();const runDir=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-limit-'));try{const urls=['/','/category','/contact','/news/article'].map(p=>new URL(p,fixture.target).href);await assert.rejects(collectRequestedPages({target:fixture.target,urls:[],runDir,config}),/1..3/);await assert.rejects(collectRequestedPages({target:fixture.target,urls,runDir,config}),/1..3/);assert.equal(fixture.requests.length,0);}finally{await fixture.close();await fs.rm(runDir,{recursive:true,force:true})}});
test('direct smoke blocks robots-disallowed and unavailable targets before collection', async () => {
  const allowed = await startFixture();
  const unavailable = await startFixture({ robotsStatus: 503 });
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'audit-smoke-robots-'));
  try {
    await assert.rejects(collectRequestedPages({ target: allowed.target, urls: [new URL('/private', allowed.target).href], runDir: path.join(root, 'disallowed'), config }), /Robots disallow/);
    assert.equal(allowed.requests.some(request => request.path === '/private'), false);
    await assert.rejects(collectRequestedPages({ target: unavailable.target, urls: [unavailable.target], runDir: path.join(root, 'unavailable'), config }), /Robots unavailable/);
    assert.equal(unavailable.requests.filter(request => request.path !== '/robots.txt').length, 0);
  } finally {
    await allowed.close();
    await unavailable.close();
    await fs.rm(root, { recursive: true, force: true });
  }
});
test('direct smoke summary uses current-run evidence and preserves prior sentinel', {timeout:30000},async t=>{const f=await startFixture();const root=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-isolation-'));const prior=path.join(root,'prior');const runDir=path.join(root,'current');await fs.mkdir(prior,{recursive:true});const sentinel=path.join(prior,'sentinel');await fs.writeFile(sentinel,'prior');t.after(async()=>{await f.close();await fs.rm(root,{recursive:true,force:true})});await collectRequestedPages({target:f.target,urls:[f.target],runDir,config});const summary=await writeSmokeSummary(runDir,[f.target]);const ids=new Set(JSON.parse(await fs.readFile(path.join(runDir,'evidence/index.json'),'utf8')).map(x=>x.evidence_id));for(const e of summary.entries)for(const id of [...e.first_viewport.evidence_ids,...e.performance_clean_load.evidence_ids,...e.scroll_stabilized.evidence_ids])assert.ok(ids.has(id));assert.equal(await fs.readFile(sentinel,'utf8'),'prior');});
test('direct smoke explicit robots allow is honored without expansion', {timeout:30000},async t=>{const f=await startFixture();const d=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-allowed-'));t.after(async()=>{await f.close();await fs.rm(d,{recursive:true,force:true})});const r=await collectRequestedPages({target:f.target,urls:[f.target],runDir:d,config});assert.equal(r.pages.length,1);assert.ok(f.requests.some(x=>x.path==='/robots.txt'));assert.equal(f.requests.some(x=>x.path==='/sitemap.xml'),false);});
test('smoke manifest records an exact read-only explicit request contract',async t=>{const f=await startFixture();const urls=[f.target,new URL('/product/glucare-plus',f.target).href];const id=`fixture-smoke-${Date.now()}`;let run;t.after(async()=>{await f.close();if(run)await fs.rm(run.runDir,{recursive:true,force:true})});run=await newAudit({target:f.target,environment:'production',mode:'production_read_only',requestedUrls:urls,viewports:config.viewports},id,'smoke');const manifest=JSON.parse(await fs.readFile(path.join(run.runDir,'manifest.json'),'utf8'));assert.equal(manifest.run_kind,'smoke');assert.deepEqual(manifest.requested_urls,urls);assert.equal(manifest.mode,'production_read_only');assert.deepEqual(manifest.safety_outcomes,{real_orders:0,real_payments:0,accounts_created:0,forms_submitted:0,website_changes:0});});
test('direct smoke records no agent, review, report, or planner stage artifacts', {timeout:30000},async t=>{const f=await startFixture();const d=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-isolation-stages-'));t.after(async()=>{await f.close();await fs.rm(d,{recursive:true,force:true})});await collectRequestedPages({target:f.target,urls:[f.target],runDir:d,config});for(const forbidden of ['agent-packets','analyses','review','reports','backlog'])await assert.rejects(fs.access(path.join(d,forbidden)));});
test('direct smoke blocks attempted telemetry before it reaches the fixture server', {timeout:30000},async t=>{const f=await startFixture();const d=await fs.mkdtemp(path.join(os.tmpdir(),'audit-smoke-telemetry-'));t.after(async()=>{await f.close();await fs.rm(d,{recursive:true,force:true})});const result=await collectRequestedPages({target:f.target,urls:[f.target],runDir:d,config});assert.equal(f.requests.some(request=>request.path==='/collect'),false);const networkEvidence=result.evidence.find(item=>item.type==='network_log'&&item.viewport==='desktop');const network=JSON.parse(await fs.readFile(path.join(d,networkEvidence.artifact),'utf8'));assert.ok(network.some(item=>item.kind==='blocked'&&/telemetry/.test(item.reason)));});
