import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath}from'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
async function save(file,data){await fs.mkdir(path.dirname(path.join(root,file)),{recursive:true});await fs.writeFile(path.join(root,file),typeof data==='string'?data:JSON.stringify(data,null,2));}
const roles={orchestrator:'SPECIALIST',checklist_normalizer:'FAST',page_classifier:'FAST',persona_first_time:'SPECIALIST',persona_high_intent:'SPECIALIST',persona_research:'SPECIALIST',persona_mobile:'SPECIALIST',ux:'SPECIALIST',conversion:'SPECIALIST',brand:'SPECIALIST',content:'SPECIALIST',health_content:'DEEP',seo:'SPECIALIST',geo_aeo:'SPECIALIST',structured_data:'SPECIALIST',performance:'SPECIALIST',analytics:'SPECIALIST',checkout:'SPECIALIST',external_technical_diagnostic:'SPECIALIST',deduplicator:'FAST',evidence_reviewer:'DEEP',contradiction_reviewer:'DEEP',master_planner:'DEEP',architecture_reviewer:'DEEP',final_quality_gate:'DEEP'};
const tiers={DEEP:{model:'gpt-6-astra',reasoning_effort:'high'},SPECIALIST:{model:'gpt-6-sol',reasoning_effort:'high'},FAST:{model:'gpt-6-luna',reasoning_effort:'medium'},NO_MODEL:{model:null,reasoning_effort:null}};
await save('config/audit.json',{target:'https://addp.vn/',environment:'production',mode:'production_read_only',AUDIT_MODE:'production_read_only',AUDIT_ALLOW_REAL_ORDER:false,AUDIT_ALLOW_DESTRUCTIVE_ACTION:false,AUDIT_ALLOW_REAL_PAYMENT:false,AUDIT_ALLOW_ACCOUNT_CREATION:false,allowRealOrder:false,allowDestructiveAction:false,allowRealPayment:false,allowAccountCreation:false,maxPages:25,maxDepth:3,requestDelayMs:700,priorityUrls:[],include:[],exclude:['/customer/','/admin/','/rest/','/graphql'],representativeSampling:true,browserExecutable:'C:/Program Files/Google/Chrome/Application/chrome.exe',viewports:[{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]});
await save('config/page-types.json',['homepage','product_detail','product_landing','category','article','article_listing','company/about','contact','cart','checkout','policy','search','other']);
await save('config/personas.json',[{id:'first_time',goal:'Understand ADDP, its principal products, trust information and route to products.'},{id:'high_intent',goal:'Find a named product and price, inspect safe route toward cart and guest checkout; stop before mutation.'},{id:'research',goal:'Inspect ingredients, benefits, evidence, FAQ, company and policies.'},{id:'mobile',goal:'Navigate and read using a 390px viewport; inspect touch controls and safe commerce paths.'}]);
await save('config/severity.json',{critical:{priority:'P0',description:'Confirmed severe immediate business/user impact'},high:{priority:'P1',description:'Major journey barrier or explicit critical business requirement'},medium:{priority:'P2',description:'Material friction or discoverability/clarity issue'},low:{priority:'P3',description:'Limited impact polish or minor consistency'}});
await save('config/standards.json',{source_of_truth:'Checklist.txt (authorized exact extraction of original XLSX)',best_practice_must_be_labelled:true,health_claims:'Do not validate medical efficacy. Review visible attribution and qualification only.',metrics:'LAB metrics must never be called FIELD. PSI threshold remains unverified without PSI/Lighthouse score.',cause_levels:['observed','probable','developer_investigation'],schema_presence_not_search_eligibility:true,ai_visibility_not_guaranteed:true});
await save('runtime/CODEX_CAPABILITIES.json',{observed_at:new Date().toISOString(),codex_version:'codex-cli 0.158.0-alpha.2.1',desktop_build:null,multi_agent_supported:true,custom_agents_supported:null,per_subagent_model_supported:true,reasoning_override_supported:true,runtime_model_verification_supported:null,available_models:['gpt-6-astra','chatgpt-web/gpt-5.6-luna','gpt-6-sol','gpt-6-luna','gpt-5.6-sol'],evidence:'Live multi_agent_v1__spawn_agent tool metadata plus accepted build-agent calls with model/reasoning parameters.',notes:['CLI version is not desktop app version.','Available models listed by live subagent tool, not assumed from public documentation.','Dispatcher does not return verified inference model metadata; requested and verified models are separate.','Custom file-based agent configuration support has not been probed.'],documentation:'https://learn.chatgpt.com/docs/agent-configuration/subagents'});
await save('runtime/MODEL_ROUTING_EFFECTIVE.json',{model_routing_status:'supported_requested_models_unverified',roles,tiers,verified_effective_models:null,executions:[{stage:'build',role:'core_builder',requested_model:'gpt-6-sol',reasoning_effort:'high',agent_id:'01a0e306-7f52-7410-8893-ff18b6a1c478'},{stage:'build',role:'collector_builder',requested_model:'gpt-6-sol',reasoning_effort:'high',agent_id:'01a0e306-7ffa-7693-9b47-56ab09bba795'},{stage:'build',role:'report_builder',requested_model:'gpt-6-sol',reasoning_effort:'high',agent_id:'01a0e306-808e-7951-ab8c-3e679af96f1d'}],escalations:[],note:'Routing parameters accepted by live dispatcher. Do not interpret requested_model as verified effective inference metadata. Deterministic operations are NO_MODEL.'});
await save('runtime/PREFLIGHT.md',`# Preflight\n\nWorkspace: D:/PhpstormProjects/addp-analys\n\nThe workspace initially contained only the three runbooks and the source XLSX. It is not a Git repository and contains no website source. No AGENTS.md was found in workspace/ancestor guidance locations.\n\n## Inputs\n\n- Master: docs/audit-prompts/00_RUN_ALL.md\n- Build: docs/audit-prompts/01_BUILD_SYSTEM.md\n- Audit: docs/audit-prompts/02_RUN_AUDIT_AND_REPORT.md (to be read after quality gate)\n- Original Checklist.txt was missing. User explicitly authorized the supplied Excel checklist as authoritative and its exact extraction into Checklist.txt. Blocker resolved. Workbook unchanged.\n- Workbook OOXML cells and sheet/cell references preserved in checklist/workbook.extracted.json.\n\n## Runtime\n\nNode 22.17.0, npm 10.5.0, Python 3.14.7; bundled Python used for extraction. Codex CLI 0.158.0-alpha.2.1. Chrome 153.0.8010.54 and Edge 154.0.4258.37 installed. Playwright/axe/Ajv/Lighthouse/cheerio initially unavailable in workspace; project dependencies are being installed. Browser capability must pass a local fixture before production collection. Live subagents expose model/reasoning overrides. See CODEX_CAPABILITIES.json.\n\n## Safety\n\nProduction read-only. No orders, payment, accounts, form submission, administrative/source access, tracking changes or upload. Production requests are deferred until system validation. Browser session/cart mutations are also blocked; downstream checks can be manual/blocked rather than false passes.\n`);
console.log('Configuration and preflight saved');
