import fs from 'node:fs/promises';
import path from 'node:path';
import { auditRoot, frameworkHash, hash } from './orchestration/pipeline.mjs';

const log = path.resolve(auditRoot, process.argv[2] || 'runtime/test-results-phase2a5-final.txt');
const output = await fs.readFile(log, 'utf8');
const match = key => Number(output.match(new RegExp(`# ${key} (\\d+)`))?.[1]);
const tests = match('tests'), passed = match('pass'), failed = match('fail');
if (!tests || failed !== 0 || passed !== tests) throw new Error('Refreeze requires a complete passing TAP log');
const [nextHash, checklistHash, prior] = await Promise.all([frameworkHash(), fs.readFile(path.join(auditRoot, '../../Checklist.txt')).then(hash), fs.readFile(path.join(auditRoot, 'runtime/PHASE_A_FROZEN.json'), 'utf8').then(JSON.parse)]);
const timestamp = new Date().toISOString();
const frozen = { frozen_at: timestamp, status: 'READY_WITH_LIMITATIONS', framework_hash: nextHash, checklist_hash: checklistHash, validation_report: 'SYSTEM_VALIDATION_REPORT.md', test_results: path.relative(auditRoot, log).replace(/\\/g,'/'), architecture_review: null, tests_passed: passed, tests_failed: failed, revalidation_reason: 'Phase 2B deterministic local validation passed: evidence-disciplined rubrics, coverage artifacts and gates, separated remediation/transformation planning, dependency rationale, and read-only safety remain frozen. No full production audit was run.', previous_framework_hash: prior.framework_hash };
const report = `# System validation report\n\nStatus: READY_WITH_LIMITATIONS\n\nRevalidated ${timestamp} by deterministic local fixture tests only. The complete TAP suite passed ${passed}/${tests}; see \`${path.relative(auditRoot, log).replace(/\\/g,'/')}\`. This freeze covers render-stabilized-v3.3 semantics, read-only mutation guards, Phase 2B coverage/final-consistency gates, evidence-only remediation planning, separate transformation planning, and bounded smoke CLI input isolation.\n\n| Gate | Result | Evidence |\n| --- | --- | --- |\n| Render v3.3 semantics | PASS | First viewport, clean LAB performance before synthetic scroll, bounded bottom stabilization, explicit reason codes. |\n| Read-only browser and commerce guard | PASS | Local fixtures block POST, unsafe GET/query, WebSocket, unsafe redirects, cart/order/payment/account actions and telemetry mutation. |\n| Coverage and publication gates | PASS | Fixture tests cover canonical product matrix, article/coverage artifacts, exact checklist statuses, and final artifact requirements. |\n| Planning separation | PASS | Accepted findings alone enter remediation; checklist/business gaps produce a separately labelled transformation plan. |\n| Model provenance | PASS | Requested/effective model claims remain guarded; unverified effective models are not inferred. |\n\nLimitations: production evidence was not rewritten and no full production audit was run. Browser metrics remain LAB only. The framework does not authorize transactions, forms, analytics events, checkout confirmation, account creation, destructive actions, or backend analytics receipt verification.\n`;
await Promise.all([fs.writeFile(path.join(auditRoot, 'runtime/PHASE_A_FROZEN.json'), `${JSON.stringify(frozen, null, 2)}\n`), fs.writeFile(path.join(auditRoot, 'SYSTEM_VALIDATION_REPORT.md'), report)]);
console.log(JSON.stringify({ status: frozen.status, framework_hash: nextHash, checklist_hash: checklistHash, tests, passed, failed }, null, 2));
